name: "hello-world"

on: push

jobs:
  hellos:
    uses: MxNxPx/gha-reusable-workflow-demo/.github/workflows/reusable-workflow.yaml@main
    with:
      command: 'echo "Hello World!"'
      var: 'Hello Again!!'
