name: "customer-workflow"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  hellos:
    uses: MxNxPx/gha-reusable-workflow-demo/.github/workflows/reusable-workflows/reusable-workflow.yaml@main
    with:
      command: 'echo "Hello World!"'
      var: 'Hello Again!!'
