name: Run Command

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      var:
        required: true
        type: string

jobs:
  step-001:
    uses: MxNxPx/gha-reusable-workflow-demo/.github/workflows/reusable-step001.yaml@main
    with: 
      command: "${{inputs.command}}"
  echo-var:
    name: 'echo-var'
    runs-on: ubuntu-latest
    needs: [step-001]
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{inputs.var}}"
