name: Step-003

#on:
#  workflow_call:
#    inputs:
#      var:
#        required: false
#        type: string

jobs:
  run-command:
    name: 'echo-short-sha'
    runs-on: ubuntu-latest
        type: string

jobs:
  run-command:
    name: 'echo-short-sha'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set Git Commit SHA
        id: set_sha
        run: echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
      - name: Display Git Commit SHA
        run: echo "The Git commit SHA is ${{ steps.set_sha.outputs.COMMIT_SHA }}"
