name: Step-002

on:
  workflow_call:
    inputs:
      var:
        required: true
        type: string

jobs:
  run-command:
    name: 'echo-var'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - run: echo "${{inputs.var}}"
