name: Pipeline

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      var:
        required: true
        type: string

jobs:
  step-001:
    uses: MxNxPx/gha-reusable-workflow-demo/.github/workflows/reusable-step001.yaml@main
    with: 
      command: "${{inputs.command}}"
  step-002:
    uses: MxNxPx/gha-reusable-workflow-demo/.github/workflows/reusable-step002.yaml@main
    needs: [step-001]
    with: 
      var: "${{inputs.var}}"
